name: Cucumbery
version: 1.1.1-dev
api-version: 1.18
main: com.jho5245.cucumbery.Cucumbery
author: jho5245
description: 굳검버리 플러그인
softdepend: [Vault, NoteBlockAPI, QuickShop, PlaceHolderAPI, mcMMO, MythicMobs, ProtocolLib, WorldEdit, WorldGuard]
website: https://cucumbery.com/

commands:
  cucumbery:
    description: 플러그인 메인 명령어입니다.
    usage: /<command> <version|reload|reloadplugin|reloaddata|update>
  itemdata:
    description: 주로 사용하는 손에 들고 있는 아이템의 정보를 봅니다.
    usage: /<command> [플레이어]
    aliases: [id, cid, citemdata]
  setdata:
    description: 주로 사용하는 손에 들고 있는 아이템의 개수/내구도/종류를 설정합니다.
    usage: /<command> <amount/durability/material> [플레이어] [명령어 출력 숨김 여부]
    aliases: [sd, csd, csetdata]
  setname:
    description: 주로 사용하는 손에 들고 있는 아이템의 이름을 설정하거나 제거합니다.
    usage: /<command> <아이템 이름|--remove>
    aliases: [sn, csn, csetname]
  setname2:
    description: 주로 사용하는 손에 들고 있는 아이템에 이름을 추가하거나 일부 지웁니다.
    usage: /<command> <추가로 입력할 이름|--지울 글자 수>
    aliases: [sn2, csn2, csetname2]
  setlore:
    description: 주로 사용하는 손에 들고 있는 아이템의 설명을 설정합니다.
    usage: /<command> <줄> <설명|--empty>
    aliases: [sl, csl, csetlore]
  setlore2:
    description: 주로 사용하는 손에 들고 있는 아이템에 설명에 글을 추가하거나 일부 지웁니다.
    usage: /<command> <줄> <추가로 입력할 설명|--지울 글자 수>
    aliases: [sl2, csl2, csetlore2]
  addlore:
    description: 주로 사용하는 손에 들고 있는 아이템에 설명을 추가합니다.
    usage: /<command> <설명|--empty>
    aliases: [al, cal, caddlore]
  deletelore:
    description: 주로 사용하는 손에 들고 있는 아이템의 설명을 제거합니다.
    usage: /<command> [줄|--all]
    aliases: [dl, cdl, cdeletelore]
  insertlore:
    description: 주로 사용하는 손에 들고 있는 아이템에 설명을 들여씁니다.
    usage: /<command> <줄> <설명|--empty>
    aliases: [il, cil, cinsertlore]
  userdata:
    description: 유저데이터의 값을 설정하거나 참조합니다
    usage: /<command> <플레이어> <키> [<값> [명령어 출력 숨김 여부]]
    aliases: [ud, cud, sud, gud, csud, cgud, cuserdata]
  nickname:
    description: 닉네임을 변경합니다.
    usage: /<command> <all|display|list> <닉네임|--off>
    aliases: [nick, cnick, cnickname, 닉네임, 닉, slrspdla, slr]
  nicknameothers:
    description: 다른 사람의 닉네임을 변경합니다.
    usage: /<command> <플레이어> <all|display|list> <명령어 출력 숨김 여부> <닉네임|--off>
    aliases: [nicks, cnicks, cnicknameothers]
  healthbar:
    description: HP바를 설정/증가/차감시킵니다.
    usage: /<command> <set|give|take> <플레이어> <값> [명령어 출력 숨김 여부]
    aliases: [shp, cshp, chealthbar]
  maxhealthpoint:
    description: 최대 HP를 설정/증가/차감시킵니다.
    usage: /<command> <set|give|take> <플레이어> <값> [HP를 최대 HP로 설정] [명령어 출력 숨김 여부]
    aliases: [mhp, cmhp, cmaxhealthpoint]
  whois:
    description: 플레이어의 정보를 봅니다.
    usage: /<command> <플레이어> [pos|name|state|stats|effect]
    aliases: [cwhois]
  whatis:
    description: 월드의 정보를 봅니다.
    usage: /<command> [월드 이름]
    aliases: [cwhatis]
  sudo:
    description: 명령어를 강제로 시행합니다.
    usage: /<command> <플레이어> <명령어 출력 숨김 여부> <[op:]명령어 [매개 변수]>
    aliases: [csudo]
  handgive:
    description: 주로 사용하는 손에 들고 있는 아이템을 다른 플레이어에게 줍니다.
    usage: /<command> <플레이어> [아이템 개수] [명령어 출력 숨김 여부]
    aliases: [hg, chg, chandgive, 주기, wnrl]
  broadcastitem:
    description: 주로 사용하는 손에 들고 있는 아이템을 모두에게 보여줍니다.
    usage: /<command> [메시지]
    aliases: [bitem, cbitem, cbroadcastitem, 아이템확성기, 아확, dkdlxpaghkrtjdrl, dkghkr]
  call:
    description: 플레이어를 호출합니다.
    usage: /<command> <플레이어>
    aliases: [ccall, 호출, 소환, ghcnf, thghks]
  enderchest:
    description: 엔더 상자를 엽니다.
    usage: /<command> [상자 주인 ID] [열어줄 플레이어] [명령어 출력 숨김 여부]
    aliases: [ec, cec, cenderchest, 엔상, 엔더상자, dpstkd, dpsejtkdwk]
  workbench:
    description: 제작대를 엽니다.
    usage: /<command> [플레이어] [명령어 출력 숨김 여부]
    aliases: [wb, cwb, cworkbench, 작업대, 제작대, 가상작업대, 가상제작대, 조합대, wkrdjqeo, wpwkreo, rktkdwkrdjqeo, rktkdwpwkreo, whgkqeo]
  trashcan:
    description: 쓰레기통을 엽니다.
    usage: /<command> [플레이어] [명령어 출력 숨김 여부] [쓰레기통 이름]
    aliases: [trash, ctrash, ctrashcan, 쓰레기통, tmfprlxhd]
  cspectate:
    description: 플레이어를 관전합니다.
    usage: /<command> <플레이어> [다른 플레이어] [게임모드 자동 변경] [권한 부족 우회] [명령어 출력 숨김 여부]
    aliases: [spec, cspec]
  citemstorage:
    description: 아이템을 콘픽에 저장합니다.
    usage: /<command> <get|give|info|list|remove|store> ...
    aliases: [cis]
  itemflag:
    description: 아이템 플래그를 추가/제거합니다.
    usage: /<command> <add|remove> <all|아이템 플래그|내구성>
    aliases: [iflag, ciflag, citemflag]
  heal:
    description: 플레이어의 HP를 회복합니다.
    usage: /<command> <플레이어> [명령어 출력 숨김 여부]
    aliases: [cheal, 회복, ghlqhr]
  feed:
    description: 플레이어의 음식 포인트와 포화도를 회복합니다.
    usage: /<command> <플레이어> [명령어 출력 숨김 여부]
    aliases: [eat, ceat, cfeed, food, cfood, 밥, qkq]
  advancedfeed:
    description: 고오오오급 음식 포인트/포화도 명령어
    usage: /<command> <set|give|take> <플레이어> <all|foodlevel|saturation> <값> [명령어 출력 숨김 여부]
    aliases: [afeed, cafeed, cadvancedfeed]
  broadcast:
    description: 모든 플레이어와 콘솔에게 메시지를 보냅니다.
    usage: /<command> <메시지>
    aliases: [bc, cbc, cbroadcast]
  sendmessage:
    description: 플레이어에게 메시지를 출력합니다.
    usage: /<command> <플레이어> <메시지>
  clearchat:
    description: 채팅창을 청소합니다.
    usage: /<command> [플레이어] [명령어 출력 숨김 여부]
    aliases: [청소채팅, 채팅청소, cjdthcoxld, coxldcjdth, cclearchat]
  advancedteleport:
    description: 고오오급 텔레포트 명령어
    usage: /<command> <플레이어> <월드 이름|~> <X|~[#]> <Y|~[#]> <Z|~[#]> [X축 회전] [Y축 회전] [운동 에너지 보존] [위치 에너지 보존] [명령어 출력 숨김 여부]
    aliases: [atp, catp, advancedtp, cadvancedtp, cadvancedteleport]
  cwarps:
    description: 모든 워프를 나열합니다.
    usage: /<command>
  cwarp:
    description: 워프 장소로 텔레포트합니다.
    usage: /<command> <워프 이름> <플레이어> [운동 에너지 보존] [위치 에너지 보존] [명령어 출력 숨김 여부]
  csetwarp:
    description: 워프를 생성합니다.
    usage: /<command> <워프 이름> [워프 표시 이름] [기존 워프 덮어 씌움] [명령어 출력 숨김 여부]
  cdelwarp:
    description: 워프를 삭제합니다.
    usage: /<command> <워프 이름> [명령어 출력 숨김 여부]
  playsoundall:
    description: 모든 플레이어에게 소리를 재생합니다.
    usage: /<command> <소리> [소리 범주] [음량] [음색] [명령어 출력 숨김 여부]
    aliases: [psa, cpsa, cplaysoundall]
  playsoundall2:
    description: 서버 라디오 들음을 활성화한 모든 플레이어에게 소리를 재생합니다.
    usage: /<command> <소리> [소리 범주] [음량] [음색] [명령어 출력 숨김 여부]
    aliases: [psa2, cpsa2, cplaysoundall2]
  cplaysound:
    description: 플레이어에게 소리를 재생합니다.
    usage: /<command> <플레이어> <소리> [소리 범주] [음량] [음색] [명령어 출력 숨김 여부]
    aliases: [cps]
  airpoint:
    description: 산소량을 설정/증가/차감시킵니다.
    usage: /<command> <set|give|take> <플레이어> <값> [명령어 출력 숨김 여부]
    aliases: [air, cair, csetair, cairpoint]
  reinforce:
    description: 강화를 합니다.
    usage: /<command> <상태|시작>
    aliases: [강화, rkdghk]
  menu:
    description: 메뉴 명령어
    usage: /<command> [플레이어] [명령어 출력 숨김 여부]
    aliases: [메뉴, apsb, capsb, ㅡ두ㅕ]
  forcechat:
    description: "플레이어에게 강제로 메시지를 채팅시킵니다. 메시지 앞에 op: 를 적으면 오피 권한으로 채팅(컬러 코드 등을 위함)할 수 있습니다"
    usage: /<command> <플레이어> <명령어 출력 숨김 여부> <[op:]메시지>
    aliases: [fchat, cforcechat, cfchat]
  setrepaircost:
    description: 아이템의 모루 합성 횟수를 변경합니다.
    usage: /<command> <모루 합성 횟수> [명령어 출력 숨김 여부]
    aliases: [setrpcost, csetrpcost, csetrepaircost]
  sethelditemslot:
    description: 단축바 슬롯을 변경합니다.
    usage: /<command> <슬롯> [플레이어] [명령어 출력 숨김 여부]
    aliases: [shis, cshis, csethelditemslot]
  swaphelditem:
    description: 주로 사용하는 손에 들고 있는 아이템을 맞바꿉니다.
    usage: /<command> [플레이어] [명령어 출력 숨김 여부]
    aliases: [shi, cshi, swapheld, cswapheld, cswaphelditem]
  getpositions:
    description: 모든 플레이어의 위치를 봅니다.
    usage: /<command> [월드]
    aliases: [getposes, cgetposes, cgetpositions]
  checkpermission:
    description: 플레이어가 해당 퍼미션 노드를 가지고 있는지 확인합니다.
    usage: /<command> <플레이어> <퍼미션 노드>
    aliases: [checkperm, ccheckperm, ccheckpermission]
  allplayer:
    description: 플레이어들의 행동을 통제합니다.
    usage: /<command> <chat|block_break|block_place|item_drop|item_pickup|item_interact|item_held|open_container_move> <check|true|false>
    aliases: [올플레이어, 통제, dhfvmffpdldj, xhdwp]
  commandpack:
    description: 명령어 팩을 실행합니다.
    usage: /<command> <execute|edit|remove> ...
    aliases: [cmdpack]
  testcommand:
    description: 테스트 명령어
    usage: /<command>
  swapteleport:
    description: 상대방과 나의 위치를 서로 맞바꿉니다.
    usage: /<command> <플레이어> [다른 플레이어] [운동 에너지 보존] [위치 에너지 보존] [명령어 출력 숨김 여부]
    aliases: [swaptp, cswaptp, cswapteleport]
  calcdistance:
    description: 서로 다른 두 플레이어와의 거리를 측정합니다.
    usage: /<command> <개체> [다른 개체] [다른 월드여도 좌표 거리만 측정]
    aliases: [calcdis, ccalcdis, ccalcdistance, calculatedis, ccalculatedis, calculatedistance, ccalculatedistance]
  checkamount:
    description: 플레이어가 해당 아이템을 얼마나 들고 있는지/얼마나 안전하게 인벤토리에 지급할 수 있는지에 대한 개수를 확인합니다.
    usage: /<command> <플레이어> <space|amount> <아이템 이름> [내구도|*]
    aliases: [ccheckamount]
  updateinventory:
    description: 플레이어의 인벤토리를 업데이트 합니다.
    usage: /<command> <플레이어> [명령어 출력 숨김 여부]
    aliases: [upinv, cupinv, updateinv, cupdateinv, cupdateinventory]
  yunnori:
    description: 윷을 던집니다.
    usage: /<command>
    aliases: [yun, cyun, 윷, 윷던지기, cyunnori]
  hat:
    description: 주로 사용하는 손에 들고 있는 아이템을 머리에 장착합니다.
    usage: /<command>
    aliases: [모자, 햇, ㅎㅁㅅ, ahwk, got]
  updatecommands:
    description: 플레이어의 명령어 리스트를 업데이트 합니다.
    usage: /<command> <플레이어> [명령어 출력 숨김 여부]
    aliases: [upcmd, cupcmd, updatecmd, cupdatecmd, cupdatecommands]
  csong:
    description: 노래
    usage: /<command> <play|stop> ...
  csong2:
    description: 플레이어에게 노래 재생
    usage: /<command> <플레이어> <play|stop> ...
  citemtag:
    description: Cucumbery 전용 아이템 태그 설정
    usage: /<command> <태그> ...
    aliases: [itag, citag, itemtag]
  howis:
    description: 서버 정보를 봅니다.
    usage: /<command>
    aliases: [chowis, 뭐야서버어케돌아가고있는겨, 서버상태를보자, 와샌즈]
  customrecipe:
    description: 커스텀 레시피 메뉴를 열거나 생성/삭제 또는 속성을 편집합니다.
    usage: /<command> <open|create|remove|edit> ...
    aliases: [rcp, crcp, crecipe, 커스텀레시피, 커스텀조합법]
  virtualchest:
    description: 가상 창고를 엽니다.
    usage: /<command> [창고 이름]
    aliases: [vc, cvc, virc, cvirc, chest, vchest, cvirtualchest]
  virtualchestadd:
    description: 주로 사용하는 손에 들고 있는 아이템을 창고에 추가합니다.
    usage: /<command> [창고 이름]
    aliases: [vca, cvca, virca, cvirca, chesta, chestadd, vchesta, vchestadd, cvirtualchestadd]
  virtualchestadmin:
    description: 다른 플에이어의 가상 창고를 엽니다.
    usage: /<command> <플레이어> [창고 이름]
    aliases: [chestadm, cchestadm, chestadmin, cchestadmin, vchestadmin, cvchestadmin, cvirtualchestadmin]
  customfix:
    description: 아이템의 내구도를 수리합니다. Vault가 있을 경우 수리 비용을 config에서 설정할 수 있으며, 크리에이티브 모드에서는 수리 비용에 상관 없이 수리할 수 있습니다.
    usage: /<command> [명령어 출력 숨김 여부]
    aliases: [fix, cfix, repair, crepair, ccustomfix, 수리, tnfl, 쳔새ㅡ럍, 럍, ㄱ데먁]
  economy:
    description: 플레이어의 소지 금액을 지급/차감/설정합니다.
    usage: /<command> <give|take|set> <플레이어> <금액> [명령어 출력 숨김 여부]
    aliases: [ceco, ceconomy]
  respawn:
    description: 죽은 플레이어를 강제로 리스폰시킵니다.
    usage: /<command> <플레이어> [명령어 출력 숨김 여부]
    aliases: [crespawn, forcerespawn, cforcerespawn]
  removebedspawnlocation:
    description: 해당 플레이어의 침대 스폰 혹은 /spawnpoint로 지정한 스폰 지점을 삭제합니다.
    usage: /<command> <플레리어 ID> [명령어 출력 숨김 여부]
    aliases: [rbsl, crbsl, cremovebedspawnlocation]
  checkconfig:
    description: config.yml 파일에 있는 설정값과 해당 설정의 자료형을 반환합니다.
    usage: /<command> <디렉터리>
    aliases: [checkcfg, ccehckcfg, ccheckconfig]
  cteleport:
    description: 다른 플레이어에게 텔레포트합니다.
    usage: /<command> <플레이어> [다른 플레이어] [명령어 출력 숨김 여부]
    aliases: [ctp]
  editcommandblock:
    description: 명령 블록의 태그를 수정합니다.
    usage: /<command> <name|command|auto|conditional> ...
    aliases: [ecb, cecb, ceditcommandblock]
  editblockdata:
    description: 아이템의 블록 데이터를 수정합니다.
    usage: /<command> <키> <값|--remove>
    aliases: [ebd, cebd, ceditblockdata]
  consolesudo:
    description: 콘솔 권한으로 명령어를 실행합니다.
    usage: /<command> <명령어>
    aliases: [cconsolesudo, cosudo]
  velocity2:
    description: 개체를 날립니다.
    usage: /<command> <x축 속력> <y축 속력> <z축 속력>
    aliases: [velo2, cvelo2, cvelocity2, 날리기2]
  quickshopaddon:
    description: QuickShop 플러그인 애드온 명령어
    usage: /<command> <상점 위치> <price|amount|type|get> ...
    aliases: [qsa, shopa]
  repeat:
    description: 명령어를 반복 실행합니다. %repeat% 플레이스 홀더로 반복된 횟수 수치를 사용할 수 있습니다.
    usage: /<command> <반복 횟수> <딜레이> <명령어>
    aliases: [crepeat]
  socialmenu:
    description: 소셜 메뉴 명령어입니다.
    usage: /<command> [플레이어]
    aliases: [csocialmenu]
  ckill2:
    description: ckill인데 닉네임도 사용 가능한 명령어입니다.
    usage: /<command> <개체>
    aliases: [kill3]
  viewinventory:
    description: 주민의 거래 목록 혹은 개체의 인벤토리를 참조합니다.
    usage: /<command> <개체>
    aliases: [viewinv, cviewinv, viewinventory]
  custommerchant:
    description: 사용자 지정 주민 거래 시스템 명령어
    usage: /<command> <create|remove|list|edit> ...
    aliases: [cmerchant, shopkeeper2, shopkeepers2]
  customeffect:
    description: waht
    usage: /<command> <give|clear|modify> <targets> ...
    aliases: [effect3, ceffect2]
  modifyexplosive:
    description: 폭발물의 불 번짐 여부나 폭발 강도를 수정합니다.
    usage: /<command> <폭발물> <fire|explode_radius> <값> [명령어 출력 숨김 여부]
    aliases: [editbomb]
  sendtoast:
    description: 플레이어에게 토스트 메시지를 보냅니다.
    usage: /<command> <플레이어> <메시지> [아이템] [유형]
    aliases: [csendtoast]
  sendbossbar:
    description: 플레이어에게 보스바 메시지를 보냅니다.
    usage: /<command> <플레이어> <메시지> [보스바 지속 시간(초)] [보스바 색상] [보스바 오버레이] [보스바 플래그]
    aliases: [csendbossbar]
  delay:
    description: 일정 시간 뒤에 명령어를 실행합니다.
    usage: /<command> <딜레이> <명령어>
    aliases: [cdelay]
  setnodamageticks:
    description: 개체의 무적 시간을 변경합니다.
    usage: /<command> <개체> <무적 시간(틱)>
    aliases: [sndt, csndt, csetnodamageticks]
  setaggro:
    description: 개체의 개체 표적을 지정합니다
    usage: /<command> <표적을 지정할 개체> <표적으로 지정할 개체> [명령어 출력 숨김 여부]
    aliases: [csetaggro]
  stash:
    description: 인벤토리가 가득 차서 소실된 아이템이 보관된 창고를 엽니다
    usage: /<command>
    aliases: [cstash]
  blockplacedata:
    description: 설치된 블록의 커스텀 nbt를 관리합니다
    usage: /<command> <위치> <info|modify|remove> ...
    aliases: [bpd, cbpd, cblockplacedata]
  splash:
    description: 던져진 물약을 즉시 깨트립니다
    usage: /<command> <물약> [명령어 출력 숨김 여부]
    aliases: [csplash]

permissions:
  cucumbery.error.hide:
    description: hides error title message
    default: false